"""rename department

Revision ID: 12af7c3cdc17
Revises: 22ea7faf557b
Create Date: 2025-06-11 11:26:20.337382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12af7c3cdc17'
down_revision = '22ea7faf557b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
